<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Iconka-Business-Finance-Gold-bar.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_temp\**" />
    <EmbeddedResource Remove="_temp\**" />
    <None Remove="_temp\**" />
    <Page Remove="_temp\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpressMvvm" Version="24.1.6" />
    <PackageReference Include="DevExpress.Xpo" Version="24.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FluentSeq\FluentSeq.csproj" />
    <ProjectReference Include="..\XTA.XData\XTA.XData.csproj" />
    <ProjectReference Include="..\XTA\XTA.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ATSA.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
