#ifndef MQL_AUTO_FORWARDS_INCLUDED_459C425B1E4F6C80
#define MQL_AUTO_FORWARDS_INCLUDED_459C425B1E4F6C80
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ABC/ABC.mq5

#line 70 "d:/Projects/ATS/ABC/ABC.mq5"
int CreateHandle(string sym, ENUM_TIMEFRAMES per, string path);
#line 136 "d:/Projects/ATS/ABC/ABC.mq5"
string GetValStr(double v);

#endif
