#ifndef MQL_AUTO_FORWARDS_INCLUDED_B78958CC300A2B70
#define MQL_AUTO_FORWARDS_INCLUDED_B78958CC300A2B70
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ABC/abcbb.mq5

#line 129 "d:/Projects/ATS/ABC/abcbb.mq5"
void DrawBandSegment(string suffix, int index, double val0, double val1, color clr);

#endif
