#ifndef MQL_AUTO_FORWARDS_INCLUDED_E29B98B3CF1882B4
#define MQL_AUTO_FORWARDS_INCLUDED_E29B98B3CF1882B4
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ATSE/CXTrade/ATS.mq5


#endif
