#ifndef MQL_AUTO_FORWARDS_INCLUDED_5DE12E1B3540FA2E
#define MQL_AUTO_FORWARDS_INCLUDED_5DE12E1B3540FA2E
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ATSE/CXTradeTest/ATSTestRunner.mq5


#endif
