#ifndef MQL_AUTO_FORWARDS_INCLUDED_45D769E0CDF19CC8
#define MQL_AUTO_FORWARDS_INCLUDED_45D769E0CDF19CC8
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5

#line 45 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
int SessionStateNameToEnum(string name);
#line 60 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
int XeStatusNameToEnum(string name);
#line 78 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
string SessionStateEnumToName(int state);
#line 94 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
string XeStatusEnumToName(int status);
#line 271 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void ProcessAction(CXTclAction* act);
#line 390 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void VerifyExpectation(int tick, CXTclExpect* exp);
#line 461 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void ExecuteTick(int tick);
#line 505 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void ExportJsonTrace();
#line 544 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void PrintSummary();

#endif
