#ifndef MQL_AUTO_FORWARDS_INCLUDED_45D769E0CDF19CC8
#define MQL_AUTO_FORWARDS_INCLUDED_45D769E0CDF19CC8
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5

#line 46 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
int SessionStateNameToEnum(string name);
#line 58 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
string SessionStateEnumToName(int state);
#line 69 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
string XeStatusEnumToName(int status);
#line 136 "d:/Projects/ATS/ATSE/CXTradeTest/CXScenarioRunner.mq5"
void ExecuteTick(int tick);

#endif
