<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>XTA.XData</AssemblyName>
    <RootNamespace>XTA.XData</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Xpo" Version="24.1.6" />
    <PackageReference Include="NLog" Version="6.1.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.2" />
  </ItemGroup>

</Project>
